name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - run: |
          env GOOS=windows GOARCH=amd64 go build -o bin/cmapi-cli-windows-amd64.exe
          env GOOS=windows GOARCH=arm64 go build -o bin/cmapi-cli-windows-arm64.exe
          env GOOS=darwin GOARCH=amd64 go build -o bin/cmapi-cli-darwin-amd64
          env GOOS=darwin GOARCH=arm64 go build -o bin/cmapi-cli-darwin-arm64
          env GOOS=linux GOARCH=amd64 go build -o bin/cmapi-cli-linux-amd64
          env GOOS=linux GOARCH=arm64 go build -o bin/cmapi-cli-linux-arm64
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            bin/*